---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials
  namespace: eoepca-storage
spec:
  encryptedData:
    password: AgB10Ah/TBcOZsG5AZpaKt8mqAiB5iej1mqMsK4b+gitN7ekRwegcJlpmOMtsE/AoukVBIBpcDmvQx2uEsXGWM+zGX0kkH0MoQp7O12G2B/hCLgdmwzPu3Qei33Sv0/1arnEVotZKzCA8m5ncQ+sWCczmLlhq2ZfIev8J46vOrn1ljQO5wEb2snCP6HNGbdaUZMWiBU2ND5IPZ+sdEY9EbSwaklnYrt5DAfijhe//jMsteIf9kr8OFf6S0/pW3gRNhx5gAk7D9JVXwXTn8Il89+4J3K/iJXSHXKm0vuqxtr77K6jKmYof7/7GVtseGm1qPR2J3io3PnIsN2+exPKbwxK4c+aailHQhjmsz4/xtHXfv/6NfVOvgKZ4pSPtTccSi5om5pOleT2LYSCp8Qwh+F3xFRQ2XA3/3mJOx/gJjpXhR205aL6zVpln76V3kEfsjQPqxJyMTl22ycH85dWZTtUOsNqOFhjLLpMg1xy36G/4EVPkZMQFI4s1wMN0VrkFtCDz6d3YsHo3Zx+sbW+8tXBqZd4xaS9LDGPaQb/bNg2FnC5Pvv+4dAM9cbc65znJuLyFMTvMV+qK8f24248v4Z6pA9DYl3rTFrvzysPTEYKYV2/pWiXblh5f/cnvWkkmEM63DFqQzis2ayYDu6QOmAUsIv+NiRpS16ydjTGeLicMq6Y5DiBrkHyZ0BcPl60+GENsBt05tj6bYm6YJqap3S/BlhdL3EuqSEavixFN2+x8gKN/Y2QFx2bQyV8CZt/f415VRVpvQpDQDENyHhq47YM
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials
      namespace: eoepca-storage

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials
  namespace: rm
spec:
  encryptedData:
    password: AgC3B4asddTb/30kOv/ArcRUgzzM8y8Nn5qifAl1/8jQ4ryTQeR38i9GU/9XRj+HjdJdg0cNCIuE1d4Xhn5B9gWV5Aa3weBa+t+wzPcnc8x1l5Pix8EEzIhTLHtUJt6tHOl7yx63GEOjC63oFbz76Uj5wMSbjhGkGIUp6bQP+G+1WiupqAgCcVwf9C3uhObirj3lucGooShO6eLegBJClq85rlWKbHxh7Jc2ycyTyyz4f0LBE0zoB6zT8Poc+sN4auQIbSzZxUYyxAs6Ll/Tg809nwE+f/r6QVK6n/lgedmNWOUDGyoeDvcluCP7ndKKu1dDwInK+Zq7ZvJ3S4FtBNLipt5pwl8WuJ1LWBlcrat+u8e50tUoGTl/ZY+rr2q1Zc+NO2OpRWDCAa9daTrtPtiv/MPqEb2ZG80o27EqCe+mYiuY7T3V3jOifs5pnml+iVz+tT3x8qXXpuADWvzf/NPTgaU30zE7AjhVSJxyfG5I1x03g/H9fzRTQtJ4HtYySqRdZ+Nt52+/DPrd3v+Vf69yUw6hpbPAeb5tBHUs/9nkhyvTIRNWYiTkw6VREp3RE/7NRLQX5CK5b52Q3yOU+KNYp3QQyqPAxWrUwAITNqO1gEuXy0bHuibT5zegLFSZGJuRW2oYKDwGJa3Z+rHtlrjWQZpsxWFZ5g3u1Zl5PTHHqRKBA3tB1+sfxOXK8PEvXM9QlRGV1xZ3XmbdBEw0LSDdvQ9hFSNiE3VTQ2mUY53WxryrIrhR6vsFM8isAXsTTooW4JXPGZyCMHaVH2bGOAQh
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials
      namespace: rm

