---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minio
  namespace: eoepca-object-storage
spec:
  interval: 2m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: eoepca-object-storage
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: eoepca-object-storage
  values:
    auth:
      existingSecret: minio-credentials

    persistence:
      storageClass: managed-nfs-storage-retain

    ingress:
      enabled: true
      hostname: console.minio.80.158.54.66.nip.io
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
        - secretName: minio-console-tls
          hosts:
            - console.minio.80.158.54.66.nip.io

    apiIngress:
      enabled: true
      hostname: minio.80.158.54.66.nip.io
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
        - secretName: minio-tls
          hosts:
            - minio.80.158.54.66.nip.io

    defaultBuckets: "eoepca, cache-bucket"