#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

sudo apt-get install -y python3-pip
python -m pip install -U pip
pip install -U wheel
pip install -U docker-compose
