version: '3'

services:
  jupyterlab:
    container_name: jupyterlab
    hostname: jupyterlab
    build:
      context: .
      dockerfile: Dockerfile
    image: eoepca/workshop
    ports:
    - "${EXPOSE_PORT}:8888"
    networks:
      - workshop
    volumes:
    - ${PWD}/workshop:/app/workshop
    command: [ "run-jupyter.sh" ]

networks:
  workshop:
    name: workshop
