#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}
trap onExit EXIT

minikube start \
  --cpus max \
  --memory 28g \
  --ports=80:80,443:443 \
  --kubernetes-version "v1.22.5"
  # --listen-address=0.0.0.0
  # --addons ingress
