apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: login-service
  namespace: um
spec:
  chart:
    spec:
      chart: login-service
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: eoepca-system
  values:
    global:
      domain: auth.workshop.eoepca.org
      nginxIp: 80.158.54.66
      namespace: um
    volumeClaim:
      name: eoepca-userman-pvc
      create: false
    config:
      domain: auth.workshop.eoepca.org
      volumeClaim:
        name: eoepca-userman-pvc
    opendj:
      # This can be useful to workaround helm 'failed to upgrade' errors due to
      # immutable fields in the 'um-login-service-persistence-init-ss' job
      # persistence:
      #   enabled: false
      volumeClaim:
        name: eoepca-userman-pvc
    oxauth:
      volumeClaim:
        name: eoepca-userman-pvc
    oxtrust:
      volumeClaim:
        name: eoepca-userman-pvc
    nginx:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - auth.workshop.eoepca.org
        tls:
          - hosts:
              - auth.workshop.eoepca.org
            secretName: login-service-tls
  timeout: 25m0s
  interval: 1m0s
