apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: login-service
  namespace: um
spec:
  chart:
    spec:
      chart: login-service
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: eoepca-system
  valuesFrom:
    - kind: Secret
      name: login-service-credentials
      valuesKey: adminPass
      targetPath: config.adminPass
    - kind: Secret
      name: login-service-credentials
      valuesKey: ldapPass
      targetPath: config.ldapPass
  values:
    global:
      domain: auth.workshop.eoepca.org
      nginxIp: 80.158.54.66
      namespace: um
    volumeClaim:
      name: eoepca-userman-pvc
      create: false
    config:
      domain: auth.workshop.eoepca.org
      volumeClaim:
        name: eoepca-userman-pvc
    opendj:
      volumeClaim:
        name: eoepca-userman-pvc
    oxauth:
      volumeClaim:
        name: eoepca-userman-pvc
    oxtrust:
      volumeClaim:
        name: eoepca-userman-pvc
    nginx:
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - auth.workshop.eoepca.org
        tls:
        - secretName: login-service-tls
          hosts:
            - auth.workshop.eoepca.org
            
  timeout: 25m0s
  interval: 1m0s
