---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pdp-engine
  namespace: um
spec:
  chart:
    spec:
      chart: pdp-engine
      version: 1.1.6
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: eoepca-system
  values:
    global:
      nginxIp: ${publicIp}
      domain: auth.${domain}
    volumeClaim:
      name: eoepca-userman-pvc
      create: false

  timeout: 1h
  interval: 1m0s
