apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: user-profile
  namespace: um
spec:
  chart:
    spec:
      chart: user-profile
      version: 1.1.6
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: eoepca-system
  values:
    global:
      domain: auth.${domain}
      nginxIp: ${publicIp}
    volumeClaim:
      name: eoepca-userman-pvc
      create: false
  timeout: 1h
  interval: 1m0s
