apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: workspace-charts
    namespace: rm
    files:
      - template-data-access.yaml
      - template-resource-catalogue.yaml
generatorOptions:
  disableNameSuffixHash: true

