---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: resource-catalogue-uma-user-agent
  namespace: rm
spec:
  encryptedData:
    client.yaml: AgCT8SiFwjNEad1xC+nEHzPC3eR9wuaLUppTa3PcOzzDifdfPAK0CxVh+8arh0jN5ryhT7Fa//7XjipWnKzrmidnolXHPvX3d0p6/W7nsyw16cgMXrsYQtKNc9qKhtIC20jwy9lKXvFphXHHWWAsR7fZ1aaUYlxgegZtjJM8Y+dkpqqsUH6y2bO8uuThm1sXWXdAP1qCzj9q5O7a8dsHOHIbT3i6D79pq8wxHy9WLkQv5xz8+7ZnR6a2akmd3YYdDTtH8P9HUNa+lPWa6X4MauBip4TwHoQm8dYmMLohpwl9Y68uA0y6v8Wq9ypZfnZU77/eXCcG2juXoEK+6kuie8WG/XIx4NwXbRFOM6b8fdFbe42AVlu3NnS1GXsKjqWw9bjR+pdtya4wKOtbqHEpc/P9ML/earA3xf42UATjyK2VJVEcRUe9WjdYxNhuXbu2FQF6Ww+ViwWsuJkvWuWl3Apy5W4f7GbtQiJ5ckQQ+PVHM3Zv/a+rEL/w4Pdx5RWUGQJ4KCXU8RS+/QGfgZNTjW+BieuO9KvlnChd3+uxQucIQVaO4DsYIfPkQfG+WHTMBj4gOrvelW4X66dScjKRHFjodkqxX7C/AkYkQY8aZy74gi93qPMBR1C0UiKDg1Xs5dzlPDsfAT61vv2a4+llWorvl/vdNNnwD2IknBbekPuPRSrkwuaMkdbD5o7McX/+eZZzp5QdwOtEbFc1tLK4Na4eBIlSJW3S5Naqcld+sIGjguVyWJrBY3uq7yE8+/dwdaJttTWA5CnvmlenK8+oO4JCsSqfb3vCTAiB8lW6oiA8yM0J62h2165cS1o4HLL6rX5RnqAH
  template:
    metadata:
      creationTimestamp: null
      name: resource-catalogue-uma-user-agent
      namespace: rm

