---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: workspace-api-uma-user-agent
  namespace: rm
spec:
  encryptedData:
    client.yaml: AgBgHDGJzzWXwKZQ6MKTpVVVxILusblNDK95jwpQZPC47soxIyjXgVC0quqeSME6uMxKtCSx5GgUg3JvtjCG/9hD54s1FSM4kKoLk/+5hD7vJMHx4rPqrJYse9O/FUZ3Z59oPAN+nJO05Y0VhKGCtj/UrlO02AHFHIQII2fdLn6C9vThvv/RgvuWohNFyLAlJ7FR3VYHI/Ci5Zg5koODp4NcaDu9ZrZMvu2JYgDMHYP/bp01ae1smdT1Y3J79g4DgWSOSaRWYt0mVr0nrJlOPov9uGpXqYpdPGLtyxjIinGjl5vniD7bSF0EmFhtGhXtDVgqLWEXbndBzPZjHYpndRIAi7ijATMr4d6Altj2r9OiEtll6rPOZG3Mj38I5ZVa+lH3/B+AW+7kYvnCUJOkOocQjm8i4Mm2jQJhC87zhmiioE56uflMZCXP+MCvkCaV6+OzrmY63pTLdjVDJdoFN2RUyH0QEKdxX7VUmRu980g4DO0mcl8jwlFve7fXyZtu7OZzOHUO9nGKh0jK/wkCGTTCBXHvW6pszIB9KBjUOX8RmtD5UsXcdkW54gg44yMUJbvkY6jFCs7RvPtRgOi0TArUm36BcQRP4H6aesaLfsYsjhCKk5ThRsJJ750dourKrFCGgx56fU2uAPk0qEqSAZbxsomRJKj1cc4UbJh7lQ+hgED/xO3gyc3IgNkjnCzCXM+uPWl20yzUs0jIve8HrxKGsVNhAu4ZoLfccu5sF1SVTeFvVXpohr2Yr89IiZGHKV0OsvL86VZnryjsJ7riiolRcRROQ2HTh0uSUgaAIDCU8P5mwi6Sh6C+dXlipEJaFDo3MWW6
  template:
    metadata:
      creationTimestamp: null
      name: workspace-api-uma-user-agent
      namespace: rm

