---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minio
  namespace: eoepca-storage
spec:
  interval: 2m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: eoepca-storage
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: eoepca-storage
  values:
    auth:
      existingSecret: minio-credentials

    persistence:
      storageClass: ${systemStorageClass}-retain

    ingress:
      enabled: true
      hostname: console.minio.${domain}
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      tls:
        - secretName: minio-console-tls
          hosts:
            - console.minio.${domain}

    apiIngress:
      enabled: true
      hostname: minio.${domain}
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      tls:
        - secretName: minio-tls
          hosts:
            - minio.${domain}

    defaultBuckets: "eoepca, cache-bucket"