apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: storage
  namespace: eoepca-storage
spec:
  chart:
    spec:
      chart: storage
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: eoepca-system
  values:
    host:
      enabled: false
    nfs:
      server:
        address: "192.168.0.222"
    domain:
      resman:
        storageClass: eoepca-nfs
      proc:
        storageClass: eoepca-nfs
      userman:
        storageClass: eoepca-nfs
  interval: 1m0s
