#!/usr/bin/env bash

ORIG_DIR="$(pwd)"
cd "$(dirname "$0")"
BIN_DIR="$(pwd)"

onExit() {
  cd "${ORIG_DIR}"
}

trap onExit EXIT

main() {
  processArgs "$@"
  checkDocker
  registerClient
}

usage() {
  echo "Usage:"
  echo "./$(basename $0) [options]"
  echo " "
  echo "options                                 | Required | Default                  | Description"
  echo "-h, --help                              | false    | N/A                      | Show this description"
  echo "-a, --auth_server <auth server address> | true     | auth.workshop.eoepca.org | The address of the auth server to register the client with"
  echo "-c, --client <client name>              | true     |                          | The name of the client"
  echo "-r, --redirect_uri <redirect uri>       | false    |                          | The redirect uri"
  echo "-l, --logout_uri <logout uri>           | false    |                          | The logout uri"
  echo
}

setDefaults() {
  auth_server="auth.workshop.eoepca.org"
}

processArgs() {
  setDefaults

  while [ $# -gt 0 ]; do
    case "$1" in
      "-a" | "--auth_server")
        shift
        auth_server="${1}"
        ;;
      "-c" | "--client")
        shift
        client_name="${1}"
        ;;
      "-r" | "--redirect_uri")
        shift
        redirect_uri="${1}"
        ;;
      "-l" | "--logout_uri")
        shift
        logout_uri="${1}"
        ;;
      "-h" | "--help")
        usage
        exit 0
        ;;
      *)
        echo "ERROR: Invalid argument ${1}" 1>&2
        usage
        exit 1
        ;;
    esac
    shift
  done

  validateArgs
}

validateArgs() {
  if [ -z "${auth_server}" ]; then
    echo "ERROR: auth_server must be set"
    usage
    exit 1
  fi
  if [ -z "${client_name}" ]; then
    echo "ERROR: client must be set"
    usage
    exit 1
  fi
}

# Check docker is installed
checkDocker() {
  if ! hash docker >/dev/null 2>&1; then
    printMsg "ERROR: docker is required" 1>&2
    exit 1
  fi
}

registerClient() {
  pushd "${ORIG_DIR}" >/dev/null
  docker run --rm ${docker_network} eoepca/client-utils "register-client ${auth_server} \"${client_name}\" ${redirect_uri} ${logout_uri}" | tee client.yaml
  popd >/dev/null
}

main "$@"