---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: object-storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: user-management
---
apiVersion: v1
kind: Namespace
metadata:
  name: processing-chaining
---
apiVersion: v1
kind: Namespace
metadata:
  name: resource-management