---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: v1
kind: Namespace
metadata:
  name: um
---
apiVersion: v1
kind: Namespace
metadata:
  name: proc
---
apiVersion: v1
kind: Namespace
metadata:
  name: rm