---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: eoepca-system
spec:
  interval: 2m
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: eoepca-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: eoepca-system
  interval: 5m
  values:
    startupapicheck:
      # The default timeout can be too short for the webhook to fully initialise
      # and determine the setup is successful in time. See:
      # - https://cert-manager.io/docs/concepts/webhook/#known-problems-and-solutions
      # - https://github.com/cert-manager/cert-manager/issues/4646
      timeout: 10m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace