---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minio
  namespace: eoepca-storage
spec:
  interval: 2m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: eoepca-storage
spec:
  interval: 15m
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: eoepca-storage
  dependsOn:
    - name: nfs-provisioner-retain
    
  values:
    imagePullSecrets:
      - name: regcred

    auth:
      existingSecret: minio-credentials

    persistence:
      storageClass: ${systemStorageClass}-retain

    ingress:
      enabled: true
      hostname: console.minio.${domain}
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: ${certificateIssuer}
        nginx.ingress.kubernetes.io/proxy-body-size: 0m
      tls: true

    apiIngress:
      enabled: true
      hostname: minio.${domain}
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: ${certificateIssuer}
        nginx.ingress.kubernetes.io/proxy-body-size: 0m
      tls: true

    defaultBuckets: "eoepca, cache-bucket"