---
apiVersion: v1
kind: Namespace
metadata:
  name: common
---
apiVersion: v1
kind: Namespace
metadata:
  name: rm
---
apiVersion: v1
kind: Namespace
metadata:
  name: proc
---
apiVersion: v1
kind: Namespace
metadata:
  name: um
