---
apiVersion: v1
kind: Secret
metadata:
  name: minio-auth
  namespace: rm
data:
  # root username = eoepca
  root-user: ZW9lcGNh          # for minio
  rootUser: ZW9lcGNh           # for bucket operator
  # root password = changeme
  root-password: Y2hhbmdlbWU=  # for minio
  rootPassword: Y2hhbmdlbWU=   # for bucket operator
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: minio
  namespace: rm
spec:
  interval: 2m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: rm
spec:
  interval: 5m 
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: rm
  values:
    auth:
      existingSecret: minio-auth

    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: minio-console.185-52-195-215.nip.io
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-staging
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
      tls: true

    apiIngress:
      enabled: true
      ingressClassName: nginx
      hostname: minio.185-52-195-215.nip.io
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-staging
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-read-timeout: '600'
      tls: true

    persistence:
      storageClass: standard

    defaultBuckets: "eoepca, cache-bucket"
