---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: minio
  namespace: minio
spec:
  interval: 2m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m 
  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: minio
  values:
    auth:
      rootUser: eoepca
      rootPassword: changeme

    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: minio-console.185-52-195-215.nip.io
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 0m

    apiIngress:
      enabled: true
      ingressClassName: nginx
      hostname: minio.185-52-195-215.nip.io
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 0m

    persistence:
      storageClass: standard

    defaultBuckets: "eoepca, cache-bucket"
