apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: resource-catalogue
  namespace: rm
spec:
  interval: 5m
  chart:
    spec:
      chart: rm-resource-catalogue
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    global:
      namespace: rm
    ingress:
      enabled: false
    db:
      volume_storage_type: standard
    pycsw:
      image:
        repository: geopython/pycsw
        pullPolicy: Always
        tag: "eoepca-staging"
      config:
        server:
          url: http://resource-catalogue.185-52-195-215.nip.io/
