apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: resource-catalogue
  namespace: rm
spec:
  interval: 5m
  chart:
    spec:
      chart: rm-resource-catalogue
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    global:
      namespace: rm
    ingress:
      enabled: false
      # name: resource-catalogue-open
      # host: resource-catalogue-open.185-52-195-215.nip.io
      # subpath_enabled: true
      # subpath: "/resource-catalogue"
      # tls_host: resource-catalogue-open.185-52-195-215.nip.io
      # tls_secret_name: resource-catalogue-open-tls
      # annotations:
      #   nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    db:
      volume_storage_type: standard
    pycsw:
      image:
        repository: geopython/pycsw
        pullPolicy: Always
        tag: "eoepca-staging"
      config:
        server:
          url: http://resource-catalogue.185-52-195-215.nip.io/
