---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: resource-catalogue-guard
  namespace: rm
spec:
  interval: 5m
  chart:
    spec:
      chart: resource-guard
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    #---------------------------------------------------------------------------
    # Global values
    #---------------------------------------------------------------------------
    global:
      context: resource-catalogue
      domain: 185-52-195-215.nip.io
      nginxIp: 185.52.195.215
      certManager:
        clusterIssuer: letsencrypt
    #---------------------------------------------------------------------------
    # PEP values
    #---------------------------------------------------------------------------
    pep-engine:
      configMap:
        asHostname: auth
        pdpHostname: auth
      volumeClaim:
        name: eoepca-resman-pvc
        create: false
    #---------------------------------------------------------------------------
    # UMA User Agent values
    #---------------------------------------------------------------------------
    uma-user-agent:
      image:
        tag: "v1.2.1"
      nginxIntegration:
        enabled: true
        hosts:
          - host: resource-catalogue
            paths:
              - path: /(.*)
                service:
                  name: resource-catalogue-service
                  port: 80
        annotations:
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/rewrite-target: /$1
      client:
        credentialsSecretName: "authz-agent"
      logging:
        level: "info"
      unauthorizedResponse: 'Bearer realm="https://portal.185-52-195-215.nip.io/oidc/authenticate/"'
      openAccess: true  # access for any authenticated user
      insecureTlsSkipVerify: true
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: authz-agent
  namespace: rm
data:
  client.yaml: Y2xpZW50LWlkOiA2MTY3NDM0MC0wZGM1LTRiYTQtYTA3MS0xOGRiNTFkMGRhMmQKY2xpZW50LXNlY3JldDogYWY2YmIwYzItNGQ1Zi00ZTZmLTgwZGMtNjAxMzdmMmRiNDFj
