---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: data-access-guard
  namespace: rm
spec:
  interval: 5m
  chart:
    spec:
      chart: resource-guard
      version: 1.2.5
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    #---------------------------------------------------------------------------
    # Global values
    #---------------------------------------------------------------------------
    global:
      context: data-access
      domain: 185-52-195-215.nip.io
      nginxIp: 185.52.195.215
      certManager:
        clusterIssuer: letsencrypt
    #---------------------------------------------------------------------------
    # PEP values
    #---------------------------------------------------------------------------
    pep-engine:
      configMap:
        asHostname: auth
        pdpHostname: auth
      volumeClaim:
        name: eoepca-resman-pvc
        create: false
    #---------------------------------------------------------------------------
    # UMA User Agent values
    #---------------------------------------------------------------------------
    uma-user-agent:
      image:
        tag: "v1.2.1"
      nginxIntegration:
        enabled: true
        hosts:
          - host: data-access
            paths:
              - path: /(ows.*)
                service:
                  name: data-access-renderer
                  port: 80
              - path: /(opensearch.*)
                service:
                  name: data-access-renderer
                  port: 80
              - path: /(coverages/metadata.*)
                service:
                  name: data-access-renderer
                  port: 80
              - path: /(admin.*)
                service:
                  name: data-access-renderer
                  port: 80
              - path: /cache/(.*)
                service:
                  name: data-access-cache
                  port: 80
              - path: /(.*)
                service:
                  name: data-access-client
                  port: 80
        annotations:
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/rewrite-target: /$1
      client:
        credentialsSecretName: "authz-agent"
      logging:
        level: "info"
      unauthorizedResponse: 'Bearer realm="https://portal.185-52-195-215.nip.io/oidc/authenticate/"'
      openAccess: true  # access for any authenticated user
      insecureTlsSkipVerify: true
# ---
# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#   name: authz-agent
#   namespace: rm
# data: {}
