apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ades
  namespace: proc
spec:
  interval: 5m
  chart:
    spec:
      chart: ades
      version: 2.0.6
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    image:
      # tag: "dev2.0.15"
      pullPolicy: Always
    workflowExecutor:
      inputs:
        STAGEIN_AWS_SERVICEURL: http://data.cloudferro.com
        STAGEIN_AWS_ACCESS_KEY_ID: test
        STAGEIN_AWS_SECRET_ACCESS_KEY: test
        STAGEIN_AWS_REGION: RegionOne
        # STAGEOUT_AWS_SERVICEURL: http://minio.185-52-195-215.nip.io
        # STAGEOUT_AWS_ACCESS_KEY_ID: eoepca
        # STAGEOUT_AWS_SECRET_ACCESS_KEY: changeme
        # STAGEOUT_AWS_REGION: us-east-1
        # STAGEOUT_OUTPUT: s3://eoepca
      # Workspace integration
      useResourceManager: "true"
      resourceManagerWorkspacePrefix: "foss4g-user"
      resourceManagerEndpoint: "https://workspace-api.185-52-195-215.nip.io"
      platformDomain: "https://auth.185-52-195-215.nip.io"
      # usernameJwtJsonPath: "user_name"
      # Kubernetes storage
      processingStorageClass: standard
      # Size of the Kubernetes Tmp Volumes
      processingVolumeTmpSize: "6Gi"
      # Size of the Kubernetes Output Volumes
      processingVolumeOutputSize: "6Gi"
      # Max ram to use for a job
      processingMaxRam: "8Gi"
      # Max number of CPU cores to use concurrently for a job
      processingMaxCores: "4"
    wps:
      pepBaseUrl: "http://ades-pep:5576"
      usePep: "false"
    persistence:
      storageClass: standard
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: ades-open.185-52-195-215.nip.io
          paths: 
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - ades-open.185-52-195-215.nip.io
          secretName: ades-open-tls
