---
apiVersion: v1
kind: Secret
metadata:
  name: harbor
  namespace: rm
type: Opaque
data:
  HARBOR_ADMIN_PASSWORD: SGFyYm9yMTIzNDU= # Harbor12345 (the default)
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: workspace-api
  namespace: rm
spec:
  interval: 5m
  chart:
    spec:
      chart: rm-workspace-api
      version: 1.3.3
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    fullnameOverride: workspace-api
    image:
      tag: "1.3-dev5"
      pullPolicy: Always
    ingress:
      enabled: false
    fluxHelmOperator:
      enabled: false
    prefixForName: "foss4g-user"
    workspaceSecretName: "bucket"
    namespaceForBucketResource: rm
    s3Endpoint: "https://minio.185-52-195-215.nip.io"
    s3Region: "RegionOne"
    harborUrl: "https://harbor.185-52-195-215.nip.io"
    harborUsername: "admin"
    harborPasswordSecretName: "harbor"
    umaClientSecretName: "authz-agent"
    umaClientSecretNamespace: rm
    workspaceChartsConfigMap: "workspace-charts"
    bucketEndpointUrl: "http://minio-bucket-api:8080/bucket"
    pepBaseUrl: "http://workspace-api-pep:5576/resources"
    autoProtectionEnabled: "True"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rm-minio-bucket-api
  namespace: rm
spec:
  interval: 5m
  chart:
    spec:
      chart: rm-minio-bucket-api
      version: 0.0.4
      sourceRef:
        kind: HelmRepository
        name: eoepca-dev
        namespace: common
  values:
    fullnameOverride: minio-bucket-api
    minIOServerEndpoint: https://minio.185-52-195-215.nip.io
    accessCredentials:
      secretName: minio-auth
