---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: login-service-credentials
  namespace: um
spec:
  encryptedData:
    adminPass: AgDddpkXy3kgUqw4jAPMddVa8NlpikOhksPyYzIc+Mr7xc7CpPz7/hyPWdkTR1UMftNymusLp3ugXxkMGo/JFOWsNCAr5chjqJNN33A4JtSHN1ePv8GaNjRCeq9PQZh9JNae7NyCcRMW9/am+UGBPLiRSqXnUzwcwN/qIVwHzKK5CP3u0K0/a8JGE7xuVtP/s1MFD90uqq5cN4PJivvisNf/FViPmx2ETrGtwLNEthrUSrQw18IwBvquU2/cv06Z1wCZCSnQRG62DXgfPG0s9bBf5hJ85zFwa+3o8Zq/gzXkRlALf1Rsp0YW38c66z0y3WkoGEtnJ5Wjgy6dPf4XIceiYakHfQmyTi4C15DlpHpv47FH1s2Fbm9aD61xn1K7qVgCcV8lYbsWtJsqZcWskwZ2py7ecCuSng4acsARAhPyA/8+XwNyijXybFeZ8J6HXclN1d4mugoHjQAAZkB+S9Fe9bOgWqj3bmKdPdfRcfrEkzZ/+yFwY7tg88jIQewNGp/0fazz0brfS2USKzBqOmYaeThVXyEYo4bY4Px3Y0FizvoVxEbhg7GYpCtiCcixLUFf/Hctre0+6/mslwM6LCgbUHbTbhzP3F56n1UX9Pxfrx+IpZaPYjjQ8hEbsK0Tku74GTuAcGtzt0N7VuZ06m23k+tqnf8TG5aCyLq8TQAzlBVvhNz9soM2A5LYF3BQqlbHcIpQPUA9sLBz0v9AND9cxqBGr1i2wYE+NaPA4BjQhaWcVTMeGWgdddsMIFATtFoLTIGGckwDC4cl765jmTIs
    ldapPass: AgAJJque9jGG+D84mRISq7+AXUSrMqln2IKSXsERXfySeSgmwowlzzwndxmNkDJZ3j9DH0YeSJj5OB9BVsUJi/B8DK4CeN2eh+Jg7nGnajXE4rbayzvNYn6n5GND1T7aRzXGkaH6+oWUsZCsMbATNxTu0vSwJkKkOO87Lwr/MsA/4CeVLRtdiltFqW5wTaKutbjyJ7nCdwlFV7m7J8vcT4UtESeIeaxdHnrPHdV8SG+UpkmKabOawn7/z91zUHG4GzOqA7WoxajsqGInOzdxnKuKsN/9iG8YCHr0YnVDScLRmoaKLIliG0O2oQFuBAzS+3EYZqnPk629yIp9BgHsp0lsMorh+lGduG0rZwfPiKSzPCBHtgTvW3Oeg484y4uStLf+OOIzwFLlr99GH6KzOPOr6ZdEQpXRRaR7dVY+3f720l3AN2/GXwBvrUJSVZPU6kXLwe5rpyNPQsTAbwKtl9IJkKUbJEWEzZvInhfa8J85bxK5Dhk7jxHxjrxkINYVGeheo9KFnY2odQpX7dQFzto8x+f13rxc0sKDUTyXtIZT7Za13SfAOToSUTl+pD2hJh/KrBf6/ijKak6zrIbCuao1L4a85oGMsC0v8V33L2jlcNiyPjJHDBag7x81oc8OvO6yVTRLIR9+ogWxW5te/3hPoAVD8HLrCYFRlVM74ScUEJN8IFe8aQo7+ePkfMnG7pdEYEb8cDNFVG7qZzx6uL/UeqB+LRfayTj/VvDWK6eIfqZZaksCEmRcDsQxG6m5uw31unWjBZxNqEWDUElY/nsf
  template:
    metadata:
      creationTimestamp: null
      name: login-service-credentials
      namespace: um

