---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: eoepca-storage
spec:
  encryptedData:
    root-password: AgAZx0w6aRTA+uAELuMYovcsBFG2plYGBmx0MYHA7zn2UrdJ6bADpSBZLsvXN5KKDqdMZ+48QCLVVAcfqUjeILR57WDvwlMIXg6KhFvKRxqCBYeaM7Ksp97McWMrvbuQnvof2knYQIPPpyesaCCxpMv/ulz+oMSLJ0PbisqcEF/SIfKeaQFSl9vsyZ5Yf+uauh+B8TDgK8hSfsXKVLqlWL2XaUEte/IA+oHvBC6JJTK2f7csj0wKfyFe+MLkKBGUpojPcrhqS2zbnI+AJSJm8M7WvFE9zZ6f8pvdbszbz6uA3n/2jZ2NacIco9nco5px+lQrQvvr9/IwvKphcXgTgTmlTDEmGVUuOM48ePUjO44cpD5PYxseYFbDte6bNTqM6lJJgN1O70rSmX9jN5AaHCSvI8137dJMbD3NPRwbyr4KcVzHZ4EPQIWU/i3Ijg6EtideCYyt/Y/PjG4Yrm9feAbEVzBC4CsxG0OMKmahGzohchLnEh/VW9ZdZRT7eDhiEm244Cky8v6DuH59NxC4tpFNab0+kV7kjLe7XL0dyPpwRsm9f0+zJC+y0qze0stAm2xZordCP1Rr/QaKtKeDcmteGLFLrnM3N9X013aDlIIm7oDTZKxKy7moOp0u1pSY7tjVF7T7k7R1k1Png0HD+yKYqjH2+HtKEdp2pijHboSoao+/5AZDdx/TwIpXyg5uc7EsSY5zt61LcMOase8kbeHDxJclK3BCd6m6T1aOjvZv9Sml0ImEAx97BQTNQhuLGMbUgdfLQmZOokHY0F0aTQQG
    root-user: AgCqt0kJ98ma5bssxfTeHX3p93pA+5g+eM5FEX/CCPtOomq1KS8N4lDPBVAJqd+YOxzpydJ206DJqG+QI/EnQBkNBB6I1oguSyLzRqiYzXbuakUCppOTOFauC9jxBznJlHU8t4lHrnH5quMYPcpbLO0w+aiHOX94EEGzQG85aymQOd6t1ppYuxc0YPfLDaBrmILVWiGeOVwnrBz4cmifcy8/BJdrCHRKpENOI1eGWxnpfWbw6VgDqfyR1eKerOT6AhNo0iCrC+HP+AwexiW7oz1EoOVdFur6lW6nJo95jitFuBHXpWp5M14ZYkMgelbQ07TeFWk1XJfyJgwccVu1oZtPpBGGvggOYX4y8pur3KuTxkaQxwiP/dh838etO+JSGzwxfGMJuvXLi3mLPgXYSRy7V4uGi2OnO9OwbArcPY5Mq/Bltob7KK1AbUikVaQPgo6krYbgizQNyXB6P62HagPMFK+h3F1DfDZl44bXl++NQQ71jOQX48R1XT2H/mp1UU3BzSRbXFMAno9D9j/c0Kc0GtYVLNaRqQPcG4GXhPcRFrnaMrt5sflTTf6Vmqb5n/U9vBNTSxIbGLDHmKNjYrft1EIgrjQjqD5nqTpr2RgJoD0WKPi+hTEV1OR7puAtJMuOCNY+gSu67jXXAd7le+GZhYFoQUuZ9MMX0KmazuAbx7DS7kH+A8HLh5O+5dSFODLlAcR3Eg==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: eoepca-storage

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: rm
spec:
  encryptedData:
    root-password: AgBsott9gaiS74z0MJiAgNln5OH4MF8BEmAxR9IBx27WksYFgmNOSIp/meSveiFj12BqCbe+KVULuVb+KSKbs3Rom69Gp060Eo2gH9WfuRamgMLdgBmvepmClHlOeIGJaeN+cBPOPxNHQZHDKShF+kKROQWRX5lZtXVwIUpiioD8P+dYCvHl7OaIfzn6xUrHbxVfAnz/BF53O/Hk99J8TQFNTU73tbvxuOFWJB+vX5E18YHVZGmzXA1PA6OhJhYIttOyOKpGaYE35vuUeMREz3u1fEJqPsivTBeH3YWqpWdq0o2QKb1nKARNSHlFG0i9ROln+CuyW0kDGOndHzdotFIZnzkeSx9TAUIPWydnAqZ8Iq0qMQAEEgfUcWSpML2f9tasPvri6hjuujfz+GQjFv/JMmaRTsnS2Y/plEmRGFbeB8A4preI3+kmnoEhvFw9taiE7Sp6Y5BkgzIMYZodHWnD+6uUaAa+MK7UV9fLYn4/Fc1ycJQaQlWD0LGgwKTVunaS+JVSCMI/o27CiAmLMccXq5vBI4CmuNvrsYBd9+cFo6zIojTUJDcYQ5xq7v2JyU+SFrsD841mf2vVqJSUswH/RqGkvteb00NP7lUSAd9y7UYYXRwzKvXZRfRvJOUcCeZqH/+NEHZfMxu7MCCUrmyiSFle8cv170LCHvTFgHAwS6wyNlFpaXb2NemG/ozRpPWbjC+FmbRdKyfK/Uu9HjJv1nnxfBBY9nBx4tgvQOTQts60tior3NWwidhtGrgxdiFqdfj4DJ7Ii04v5QpByRcO
    root-user: AgCuTV3OCCYq14vj7RH8JJNuNJ2Lyk1PJNGUPfJBTSgefEgXkFhGc81NxLtwAHux+w14xJZvw6ny+QR1+vRdGnXPmpwSPiFZlgoBz8fWZghk7udPY0gCspyvni7osE4t3DNrp1XIrfWtdXAtOjZFv8d9n3NvsxflFturB5nktaN44XCkKaXH+RMjawQcUepU/HSGSjqQjv+nS4FW2CsqvB/nH42rJu7sfQ4uJAKAOeyzFAbOh8UyhzrnJ58SbRmSblELiBRvzcRxXhGSvwMyXebsnpfnKSWJ1Tr3B5YURQ6dTPEfvOiXLEWKpN1QAbmZxsPsq+uWkjal4I3NnFMnEt6wgvuJfLTZRaqIP0lZlEyF4LSB48k12ZSfoEUyNtn1voIze+JBQ58jM0dkgGB1nsff/DyRTlHnr1+qE/MJK3YnrHb8b9gMAg5tK9BjPjA8yZdGmBYDJgUIwrDDwSeNFF3geesNCjtmkTeZei2DA3NXxm+BH8qhJzmXI5jpN9KowLIvV1SvN5FpnCnCIt9ifSBSG2MJE0Rb2HZmwWRX7cYL2t+HW2rZyKM3+YxaskkSAYC2zEAVEMJXD2oC+Q//ka7IZ8zGzDZr+MEvC4QRwWe147mj7Oku9yNHV37aLAhDZY3DTU53wS6JrNkWLtx1JBQy2UqFUTi/m6tUDJa8GH13p1wowD6MJWfeZckVmJrAv+K2ifedvQ==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: rm

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: proc
spec:
  encryptedData:
    root-password: AgAlB6KpsaRb/QDYXhUwHUcv+7BlT3eam+fsY/iy2ETGbaNC9iBjHx3svnx7gvvcgll5FFempde6/XCNfCY9RSubeAGnVCgW2PsI63DogmZpJgkvhRWQRcyQ5jLRo1VdmIrehlgXAyfjchbFIsvtIGj60iagIlRp0TStZgStSQBY+rgCc3sNISleIMBnwTf8S1LkpTEPSjguBjyaDAYY2L+sntvm5WHtZx/t2DfOrc277fI3rX5qmj0M7znI7d9ogxRy5PM2EyBlSaSPOEpQADG80G/abZE1a4ggv30ysntjFn6hEU04q4h49bLJVY0mUyLZ33a7AaaxEXh8DhC7HF6VK7kMZ/VMah7KcySgbwm60qoPG3qZ1RqdxOjLGRqmZvCaDa3pDF1lYkschjJy/uNJJq7sLuBnO64N53U6mm7TwZ9LZ+G8Pb8h3d8G2FVtGAX6NYVmQ8vHwE8ilmN2GCTvjrcenb0Wo0q6nqeeQhAvCWyaMo+oeOCyRM7DNDkVC3qrcDi566O/VRJnJ/6N3B1PmP71mvFY7VYviT9KPIjMKNvw5MT1w9/O+okQUTlUbpd+5+0L5jkP0Bc+JAUXPZWj7J3sWyOq2oVWFQNsPEi2Sc8W6Uk8gW/wRlqbWRpe4Mc2QJNfnWE1GugNynK48ZJbL6UXgMSLsiQz09Xts9vorQs4lDe7665ea8DsWQl79/j5DFLMDQs44s6pWcEwtcNotPGK2N1aKrTNYOUjHi9J/ixtlIEI0uEYE8pn2vj0CRllhX0peVsD7fcUCYJ3Kqlt
    root-user: AgCmG2WK/meJjL8k+HLAALAcsCjqPsF8YzfRKZqhyQ6JrIE6aqsGxRM8vA37m5OcJh6VC2qRb88UqEm1ahEvum5p9JaKuu21FDPCyX/AFEb+UOfdGRtiQPfOOIojYpbIIzeGbO33tsaWGYBg9svHZIO/7RJyrwu8CS4T7+a3LhselBY9wMNCnKpBlKe6ipgr8wJm3btNjsxgRopPQ+fox0E2dzgmaEpndVE7YsbqWR+zyQ1rhFlQGgRYVwTFhT53RV2T+K6qfJKGZR9bTqhZs9y3Up9HSjDO17WuA5lp14zUEScEWgPztxFn/HnRVRjf0WoDPxWtxJ1SKI844N5LpyVoHSi7m9JCZ1RHrQxo/9onCEzZnFGo9LgoeSp8dTXLvxpW5YrWIllS3cm/22jJgjFOkzbcF6VqUA8jGt17MQ9RjNlaLlYjodANDZprUPw/j2jk1tpCvCPtkdEMqTNU8gsv1CYrOlwS9D+QKuH+nZwUsG44Qo8z3vno9cr3s+MU6/s9Dm0qcrqqqq7rR5iapjbnyKmDOpu1+CEL/h8WdXUxJxBjBRLSnoKsGA4lViVTU1WfA/K68zSt8jcgl/oFuQP4+7N+ABNIUotb3V0llsh/rltIKg5eRC01mqyJvcbAqMCtC+vx9BIJCZe7bpnLBbGTmD4eNNtaxC7wMsfWtGsfwJRg1jNvVmuZcOZz68gn8GoN1/YzWw==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: proc

