---
apiVersion: v1
kind: Namespace
metadata:
  name: eoepca-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: eoepca-storage
---
apiVersion: v1
kind: Namespace
metadata:
  name: um
---
apiVersion: v1
kind: Namespace
metadata:
  name: proc
---
apiVersion: v1
kind: Namespace
metadata:
  name: rm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eoepca-configuration
  namespace: eoepca-system
data:
  publicIp: 80.158.54.66
  domain: workshop.eoepca.org
  systemStorageClass: managed-nfs-storage
  nfsServerIp: 192.168.0.222
  certificateIssuer: letsencrypt-staging
  workspaceUserPrefix: develop-user
  stageoutToWorkspace: "false"
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: eoepca
  namespace: eoepca-system
spec:
  interval: 2m
  url: https://eoepca.github.io/helm-charts-dev/