---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pipeline
  namespace: eoepca-system
spec:
  interval: 10m
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./deployment/pipeline"
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: eoepca-configuration
  patches:
    - patch: |
        target:
          kind: Kustomization
          name: "*"
          namespace: eoepca-system
        patch: |
          - op: add
            path: /spec
            value: postBuild:
                    substituteFrom:
                      - kind: ConfigMap
                        name: eoepca-configuration
  prune: true
  wait: true