---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: eoepca-system
spec:
  interval: 10m
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./deployment/infrastructure/controllers/mundi"
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: eoepca-configuration
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-configs
  namespace: eoepca-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./deployment/infrastructure/configs/mundi"
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: eoepca-configuration
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: eoepca-system
spec:
  dependsOn:
    - name: infra-configs
  interval: 30m
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./deployment/apps/mundi"
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: eoepca-configuration
  prune: true