---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portal
  namespace: proc
spec:
  chart:
    spec:
      chart: django-portal
      version: 1.0.7
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: eoepca-system
  values:
    domain: ${domain}
    authHost: auth
    configmap:
      user_prefix: ${workspaceUserPrefix}
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: ${certificateIssuer}
  interval: 1m0s
