---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials
  namespace: eoepca-storage
spec:
  encryptedData:
    password: AgBHSP+PVY94HragaZenGgj/UX/04Inkh8Ca0SDmqTo+4ht3hC2sr8GPp8W49DgFc9uqTMS44jnNOz6slJI8XwZQLsMG3vw46vnZxULsd+bJDmgu0RYtIhzi5XlllQIMHz06Fs4yTsBtKW5XlRD86xBaUu6+zrecXWPR+rQOQYBPnfc8dg8bpd3HE6XPnK+WMRhBwsxEpGvhEvGm1EK/Ath9Mnc1DzujCHWIZKKtcbEonByKSVH909/wagL5AXK+t4UK5wd3vsxbkbG32n4RwKvehfAWvbbNZuyrn3y7RTBsRKoS0+ctgOhWuziCXMgd5SfZ0vChNdVADL8+6mw6n/6mteYrk8xlae5nZDK87RO7cluPXoL2FjTGc4AkFerlxfUAU4JBCORPzff61wlXGNiiks1lDAJqfAHb8/CtewWXUl5GuORm2WCDS3ShJLe9FEGeKcQjs8+rUX6v5J+Q8mNFsy8jeQu4vv6PltwfBqJOCfXOWpNfXUgzSFNTn0WY94erH9ne5qxiUgg9jkW96T1LZyU3qAZYARVZSyQTJu/9WsXLnR2pggTfLYEcnGkumttU+ORVxIZsnC9y/ZE7Zw4uA4D59PYya8SfIl1j1UPt+RkwEovkg9nheoYvqyrcl9m06hy0Cu9l83u/m2jJowtToOR8Fsvjn9vLcU5m5tr3yWVoxs9B9fFv/tvdjBMesEDUKolrkCIhYQjb3TuyWXcwB4qgq1gSHNOAQixQTQMX9NRuo/uxeyKNoAK7kSDJze52yIhHq7JODebtEXnlxWBw
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials
      namespace: eoepca-storage

