---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: eoepca-storage
spec:
  encryptedData:
    root-password: AgCIxoOF7fx22uPwWxtCqUPGd89GG6Nh8HVw6cbS1/dhBSvSL3iJkjBSs7H9Jgf5HbxjiqJ9OFi6uL3B0w+L3J5zmWaOSnwKXz1MPbmSn4JoO1c4r1fJ0XGR9ABBTkPreHHl6SxjSHqccEgnII3nLPIc1YZVXY/++/1dlNUmsXFRzV8jUNBbaFQ+WWv/N2hXVy5MgYsSoicTUIy65gQcOrGO73nwYoo67SPxtpLAQrfJsT65eQEUyG/qqbxht4OaI6Fl+lzqfUxlWCYZdUm5bfEHQ6RR0ZZSuNgLFnVo3iC10Q2bUx4+IU+FQmZPSgz0KLT5auJxE1b4hllG/kCAzrmllRVwV8BT+dd8T0bBOWWW2e8a46uiVEkuGRcnotSLyzifSRHaNk+up2BPGdn6JwLExEqJT2z4JQQCCePC+31oq/zk5pFnSDv8DX0QcAnWhaSatDH/NJZPT1PnKDD8jkf8ddF15qCeBi1MZdBwqYOzxhD4k91n7Zvi+Mw1kvg2tbcP03ZrpILhHl/K2Hbo1eKmmofDsUo+c9KL+rmz7BvjEoArv0zsVpE16wr2iABkgV8v9Bylj5KJ9r90JHxGzRWI7jOcUa7w7GROSVw29tWu9WPkBfYWBWji3DEtO92/zHVo20VThkzLlhcLzO+UFjNHQa4ZLh28eRStLEfCCTvXdy0KPGRSHlN93ZW3r+MXfQdTbJeSDUu5wl37D+lGbtJmyz3c77wmAeayNHm1i5tHhXowUJykA/WUCH1qWBzQLGgvRrVM8H/XaxUmmZwf0kKX
    root-user: AgBmp9s6wyzvNYLoyz8ExveeORqOpPEVyvj2gB8kpz32seuV37eFaeExIbHLgIXp3n2qC2Lx/fuMYsKRCne6RlbtsjkLNhf0mCOO/zmH2iIgF/u2rQ20D4UH/ja5YicVOdPr2A6ykbt3Xt4yejHRWw0TjrlVVkWeOADhuf97wJgjyPJeVX2UsGAU4l4jasHsg3X1XaPJtt4YzxmG7QA+xsAbH7v5AazOQX4D6KTIgOuJaxdLxlqPWXeuF//wDcQbm3XIhghyO2WsN8PjESJz+MJkK/X+/2jlAhemPEl1hwuu7s5UjdQByqPwHru75Vy8PvtGiF9AiDeqzLgm/88zqDB6RngzrIMVg55n3BM2z+CYpmWk8h7R5ASpFYln7aailLN61SsggbQ4/GNbQrIz8UbYzYWpSaINWBP1wcdkwVRqgo42V03VWnZMWepaDMeppW8nynqFzi/lvqYXRWB7dEktRwJ5Dx3o9dIGaNZgSXT6WErSqPn12Vcd5GUq7shYsGQ6aiTQ0/XKPohEdYH0CRdBtKyctJ/DCYHUOb8sH2EGrM31rWDPyaPeKJEFDL3Jymh2rVmmV3IIToB82sjbXW5Shhx0ElxvapwgmDZLDscBKiS7cgVFRvON8POUVkE5IcPBjeYzl1kCVbvb5mHh/ccOB8v260kW+i/xoXXF7VrC0PGHmyucHPJPpwD+n2PV2soIcFWzmA==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: eoepca-storage

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: rm
spec:
  encryptedData:
    root-password: AgBMX03Go0zKqHnRfNL7hWspSQk1Ec9HVu2aYnTpSHxPz0/YdokPivYYK6lcnDMDUyRz7g0Zt2dAJFMLPKfqt0BcmqVlnikaCO6CnUFow0JuYx61KMNmEDIvVeD4f2ReYH6K6jP1wD7FB6daviAFUidPQ2LVhY2ZuSG2hGtpRfcsVCsmKgO8tM1A22G8sj7RwJuig8AjurGTDCIjVJ+6B77b8niHnqqLns8D6/ly7G1vUGDq9S7Oe0epXFWxUd6BrNk855Hx+cFC7jYjk1l7wzXCVD+EeC1C2mww+1l6xTEX5NfFLdJyUqEm5sw31GvkHrV6gFpVNxUj78d1I39kqCRcUy6U4zGZvW7iC1Ue6c3VUadSRv7HlgRFnIoJafO5NoUsWHxevVj2prwyay81wMPPk2Ia2lCjKnFB1JUZCQ3WQytP11RooH1PXvRCZEtpd35gohOyxFt9XobPYfrYi8Ompkz8+ieYTUCC/QkGrG51/YCZyHOPy/mps6VoOy79p9EsKfEg5b2GjmNwPAWwgxLl/rj9fMKQ8hUi7Cf0FE5/w2r3E3FqeztvZkWYf/bTZVS65K6dPZ0gSp6WXTcPKHDfIeKC9vVLMUDt+6WNOfWBrYa3MtlDohdPYPxktOfbA3yqvGBZIFKptLbqySPt8uFlK35lrzUhy7w8Gc2qRfDJ1HJvN0viWAoj4yZ1GF+UoTJHaivJahrk+MiX7/5I7zvy55inBFDUzSF//c8/2kSp5/kwR3IgLcKfYq6C3GfcZXg9OChqdu8liW41a4TG4fPx
    root-user: AgCYgaZ45kc9/E4lLsRRUn+K+JyTbhb3v0M+BIlPjvh2VOAb8VFFdjfWA4LlLWcRbl6n33Lnxdbbs+3eSdgb5tCapFaUzsKp8Iliiiq2kif7Kmfi25rutYrxa4dAjSJ6pjx0mgKYGLw0zEW1fCnapadt4CPVpGFMq1VerIBUeBMc3wzn+Z7I1j8uAlyB2xD8F/n8ltI+ER0B227qIht4PKFf/9GYYj9xPTGdisuiqacuqNlkqxDFW5iYbJO2BqpSzVrgAEHZpAn05psVJxFMPptbTBDJ0KRc8vbqT2KSo5cRjhdlPQv/7yKR2N2LP5670Zxajizb5VLxk5T+yb9bgBwQKXBFLMYHRmJxPMizv8wfqN1ZMLAzJDHcokq/IM7bj7QP+fkXKc2jcgDWznAP/ZtyO4EElQ9w8I5Tznc7JhsO8kd4TUFe9m8vKLq2lYugcG9++z8Tc4JHQsQFRUCZVHyunfU+bnU4hWYFO8WItk6vXOobPGMDG3+XWKTlaFodPYbw3MuZocgUm4pm6xUBdH9GZTNrEzuLG/B1Fb97e+ayLMyRsUBMfZi90wxNjjiuqGriqr+6oQSXjo0oIY6cjd1G3maT/fYEgS/tiWTk8t8hLwI90CHr1qgxEAxLZCQJ96+/iR6w20ZUM6KLxvzvll3DV45YIZ7cIWBokIViZIwdP1+6YSlnWE7MAffcnYV9DmIyU58YFQ==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: rm

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: proc
spec:
  encryptedData:
    root-password: AgATExfQhiBVEqDnZZGdfDECIoO+IU5ffd+rVjFvucFbXiEDP1exvKxtirZZ98mDw0ZmWrMUwauNHf7qSlWKLAsUOnQOpvrlt9njlETN6SgSTWtYg2zrItmDKunMWFNb0r9a1kpbY/2cUTf5RNW9n3mtVnYDFZGSe4IpQAl+379rQpePU/ryBETSNYsOgUyS5QEnyMH0Dy4GxP39Q+PrZgyEsvxDQWmwT6bkS0ik1EkRdHiZDmXqHzb7yjs3/KBNPZO/cjBRE816etJA/beTjE3dQU5rLpqMiqV9HOtbH0eVv8sTTkSTfZAw5iBeSP4V/12ewOcDfzjQm6WOxVcoZ2tbS4C9eqFDe8jnvBJobkpIihXNAKsg3HIKkZGvL7rP9qJWkrE8tGlpa0V8a171aoqjp/3pqUIJkq7jvqvDI995XK1J2f074N3O0RIdO8HvRtK+PTCYGpM9iccT1a/kQnPNrwh3xTd7KM/iBnlkYOCyfWMT/L9fkRJE4NkyKJ5BjDpjVKP1KMV5N8uZ79bhKEo4n4Zk8cLur2rygjwHm6CPjNrwnoDiwgl0fDxQUXsrHG4Pr+iNjGvGPqWSiPaGLjfqUxUjXi31KatX0MCV91EXBTEEnhaheFQMAEIjTSNbt2QfIlKXHq9F3ayQV8f+ehTBKcuBxtnGu07XkwfkDHwDQ76yMXbJhxZE2niA7hj6t77qw+3HFfMO3yIJpLWWpoff95iC/+qfpodiVruh1oqQG+Hu/7qH7DCInn0nH/X61ZnuALReQARBmW/LY3HxEcK0
    root-user: AgAoh4YDZ6oPAuLhM0kAxBGa1RQ1Vu/H3F/RzAPNkQENTHcL2s4oVYhYtvo7X7MKMJkMDnj+m+7uSIimMEAgVnGcDtaaHOTG8kyFJFh2WeullcSqmso93wrBGmSdCPCx3zjg+9cG8oh+K1asOEcTHWCYEq1/YPOjgMsKzbgrIi6hdFIZivXhiCWDsS6D1IU3eVFCAbXC9icZMyc9wyzKBqVL7I+lpYfX3dIqKRGyCoe57hjEIUhVqAAcVCIvniP48ZxTQjtIMHrEbbsUtu0hGCIOKGHTFtGmGMTrsakR1K8WBw1WSRthlHxJUGCNN8nqKwf3i86x0xmx7++lKqypMn7yKAh/xh87CrrPCv1ApQ//HzGc5qip04MCUFn2pb0K3IjVgPUpZdxAQ+dgmxSYH0Iw3lCEZzZEqxWpizzweaxBRNVB+34vf0sMOZwuRvzzut38bBi9vUV3nNXoAuMdcvMhgVVtcWLSFNTtSnolMKU0fY/K4pl8TUWFD1DbxoX54NtXpXgggSlVJPgbyN5Hmt3kFfHIB3VcoS0IkPj0VDYE032IyhQ+1IrFQfGbwGHjSZHLiUiQAWGUp5+t42G1EHMprawMiLbmalkn4oIn4ca2naIo3LR4Pyh+0YJyt9gygw9J2zE7RJc3E+FDijPo4j8X89BdGwIhlBn4tj5PS/gSatGJiZzHZA7wRh4gtVzC+3yNk7iV7w==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: proc

