apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: eoepca-object-storage
spec:
  encryptedData:
    root-password: AgChMUxkNdvbS2A+G7voTAW4r6LLZDvINM+cAzlbzmFK3iHMM0HqINcY7Z1gSbZFXwmTiQKwtgPp8kjs1RvdhJZ9Vw/eKDPTefmGo9V7cRNzrLXUmit3Bf0sDO1DOu7Y6A+c6UDiWrC95oT6s1BZ6tbrvtrSOGnm8mxctnv9Jt+PB+8j4bkluM382VdJl+lJwMJyvPGbCyW2QoqJhgGArl245bPMn0ouU9hnhaep0cuC799pYh/5yWWvLPEF83zKdR7xNDtkcF6j6W7aUBY3d5FrxdE7TCIhr7QtWRMphqPU558xolu7lLB38DJsk3+s8YN68CvO5eAXTNKy8T1WeM4LMGtNEB07bS35loeUvB4j+fOGZp7xOSVh5G/5w4eCZksHD6tyU5RYz92S72sZ6y8dToNN6Snzv2LLZ7Qe5EmQ8Mtx0VJRMW8wZn4qD2BUPXr19oWgQKyv6fOR8DRQhbi+hDYf7+hLZQJ1GUsBZHFoRNnCm1lXv6M3VG6BfrVCvaPLHGH2nIUCOsXWXckTBxLRjMdDvLB9cjzpeJh6IqLW/o+r4ifgn/3aUNsVUgOzbxhfz25pCBmKHDarIcFHJorQZtELCllc0PP5L4A5pcMjf+LhhkIcahavp6HTQZqx933spUWlWs1LO82y79m+M17JMbYQ/M4sbHUtBHpnF7uw4URC13QBfmZgPm17FxHxd4Afyz3VrpLkSt7zk8N2+wovhCnPLG9kFPzaPNHSAlMtAsPUj4kX5To5CeqhUVxpS1AnGTWTJwwGvF863+Oy/6VP
    root-user: AgAUMEkQHwOXdQ5MKamylWZ/GwF9oKT6v6ic4C99uXRy0vBuIjQNLm4g9oZ/6QW+zUaW0DRALYOz/DA5cuQNhHdFJxYC6kYrhg3y4nU8Osc0LQa0VitQfeiRY6/WT0qGsXPgX8JGgeISekM3sdBhMQJ2cNLKDQcLgWmW5NPVoTHJFJE4i3wKHB7e2AfCdpto7ZjAJu+PxXTRQx0BmODen4SBBKC+vgUFJ910ObYIfTOWawsDqwAtkNZcHUXpAxYpLqMDA65cclxdzIq25Mif/+CwZiH3LLOs4V/ktjYShppFETGdqeSG8gdyUMSyuSYaz2h/1UGLDZjDSJj9IkHBoDLhMbuBwjTY/3fV2yHmgGnQD+yNVQ2rjJiuNQgNs+Xd60j374HL9m5pv2CdLbIk2+gktZYhPyJNqeULCu/MkFIiNkiCmEyT5WitHX8ykxZ8ZOXPgJu0vzAsEqWNdwt3vrmXbh1ljVKADMngZm6IxdX4rvNvSkVsdHaF22BC3MqEsiGQDSL0hkhb3O7fXHSMWt7gyWI8Vcr3LfUkJRzquJOG1xliHed+FNr50Vm5mGdczYqZuC/iaQB7mCXK2NsslKBV94gvtnUjeiqsC56fR/VLUFP2KryeHDgWrK2g+VPK+MRuE144Ct2JDfyq6PDgE4vhVRhWh6uxetrCs0p4jNbTLgt5Y9OkEQvPn2Jm81VSKDdKibboOg==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: eoepca-object-storage

