---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: eoepca-storage
spec:
  encryptedData:
    root-password: AgAZO/X3+4cceRZqSBcQLak0Tl2EPi+usalatALVESgj8YAp15I4N8INuLc3C6I5gPAtinditKC5OAf1XOgNRiZwKEg5mIPiX1nMFAC1fDRDE3fuRWwfcRpauWGXjRyjudxiEwIE62BRYDcEG7ZyFROreb1Q7rd8QCxE5VPnM01EX+iHoMDUaauL8qXfxd5Xe+fyYRCN4qoE9C6tkehgA5r4+QYgpqKVGkaaSbrtxNozebZOqYVL5lbvOcG3pZyQDBoEdT0qotDXikkBj957z1a6ljHddKo6ra2rzMR/2K9NaLI5moXzw+wlGn4/rU0rgBqLHH4j/7rsVkwpdXUo0NjCVsN5EQs6Qaohm2noh/RamOcKMuiV959zYZCx2zkkXpFFYIUTQJb5F314Rdu1yFH2HAmdehCmJDaOftRSPrpRuZ3NEQv6AYecB0LZ/nXXcU27WcPLnXFShqvRt8e0gfqxZSX6ua4oThPe0JntmGWcc1Vn0kvO5ELfm+wLKUVMyiJ79D5ekDGV4GlJW/f8tzla6zN8RlCJ/keL2OhwwJoj7oIE53ckYSbetVM55fcqs7N3lNcjiIxNT9kTDcIqaUN4elyA6iVA4CtAHIdD6lLcO1bZyuWHx7GkCUCiy18t9q662GE4dxtlPX6cEh4P/9phhGDpstRU9UAEUBrB6sxBUc76H0blhaAP2BUSyd44ZlKZ+4pJClqu09ezTcgQ6A5KlLCgYwM00J24ZsGTgBVXRnb3nRVypwVAtepIEOSq0aTnzKkmZY4J8M/1dL3QJ+aQ
    root-user: AgBA1XoD3es5a+MwEJOw63X440kDF6hpKeyD2yL2XcgQApYhH6xmIH5FbFoIzXfrAUoZHsLPze5H4lKb2WJEYKK2FwS+Bf9tdeq3T588nnbBPfIsIjtlE+bSmDyu22NGV//d7oK8acxagtpnmNN5dlNg9gl9djVc3tcN7Hc4x2B36FQotjXWKP95oElc0L4t67yd4GpuBZIrtsJoTdQI5r4ewKq/shV68IfA+ybgEaBkL/7OHcqwX+Iyea0v+l+mr37AU5kAqRRqL1gkboSwlaJ2CLdBDd5kwu5DqP9AGo9jJSEcMXHlcK5l6W15OIE1CKBdoqyOeabVjWwcRkSLA5p0+NNJlqexaW6m4kxMrlYZPTzMOg7M0g5wu1EPD61MUwEmodTeSJzss6FzKCgRNV/phnUp5IkKLlFV3U2Rbmaz1HpZxiPgUw2QMrCC10KMn+i+F1W/vFHpqI54FZEe8/O4i7PSoqUBU7C1bPZK7LVtAE1ID5uTrgpCNZKzHXIkpGiGSjhfzOAWQIO8aF/jfgxuZZ/Rn35jU2vAYYkZ+O5XTPIDrtsWWEbyCcheFrCTHFcvvO8KPhSYY5QQzCSeWkHmoirwcM//YeqSKZ/gOIn8Ychv+JIeHtBW5b/e2dSbni79wxngW048XKrhHO3TSbhjb3mnuhVU4UymIoR6IEwhX/++kq6W5k+/bxMiWZAzb12WekFGig==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: eoepca-storage

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: rm
spec:
  encryptedData:
    root-password: AgA9somn2YgyWJX2Z01htAuk/41DPUDf7OVyFJAZSY8R9GR68M7V9Bj0G5w4wYtlqZPgvXNigDT/ScDQdZdroiVVHUN775F8tPvl7x3ChvtT6ka4ZAlS/8ojK2XZcgIvrS+Erq7bCBN0gWjF7FUKFn0EWab0lWiE1pLLNPIJ4PPGkkLVcrhrOfOc39aEO8NA6XRyLruZ5OUke0/0mE/4eBm+W3ZFDFp0aHtMjMOWH0k2Mc39KTzUPJ7grVVut9Wt0MzNPQ+h72uu6bIzS1+daZgWIMbCXdq7PVpkzaIajns3Ae+dVDJizi3gItFn+bmruA98rymt+UpwsnYFnScki1vzjeKZxLMl/8ItGBaWJv7c7LWdE4wBJjVSOCZtjlafirf0VK9RerFzLOgsU6omsdjOxTIjGs0qusCuyKybKff+08sXDv/cVI7tUVoaB2pUQFwUlW8LOUgPnRg00e2diJlYgmop4B1u//GB4URfrLZWiGHlyf6RW0lMfyJYMKiSQjnHsDNWMgT+trcjA3hucaKgZ2cD758VnzUobZxdt49pm8Ciz0lxt4hOpQe5SmmCEVOX3t03sdjAkdUbxzJZOFEMn6vBe9cJfHxm3tCSN0vkEHxN61lT1BV1p87YuSFUJVPa42zlI2LsAL+7HMmeyHJHTXzZrbBH/u4cf7t4y2rxagz0RbgYZCM6NtzROOKvn31YdyAhYIdOmbT+HVAYUf5kN9+dw3vRyyD6xjPymDL50gwVHPh/KuUePGWRYX/G4VOSXH/Q6Gq5iJOb8gwTcLjz
    root-user: AgCbsmDt6NMNJrVl3y+iDIHThB77rSN0gHVp0U13VIXfO9MHbWg/IEqcUoLz78E01scg8ipE9WU61AHp2YjYeKDbuB1wAZvCsnQMgAVFeoDwg7PKhjpoaoqNN83uqXYYeqki6KjxWMSLiiUK/wBYTnSl39QniDQ+pd/xHd8DewYc6XnrurQfuHkbAtS8nKf+izx07XWJR1CRtpT+/ze4VJg2xaRyLI0VVY35f4xQTj7B83lvMBQNVLU1+TC6ogc9wQnKLZGOowPEA8s6V5pkT173bOKAd+pJpfEgroLxVebVx1ctJLbOvEwQL+/pKAAE/AzWAse855ZulPnbo6vv5zQJopTfaZjIMPvdBpxuYS7AI1V1gGsjkynMrvbNDVGVWzYRb/d9UE1edpxY0ypj1SJDBm7ipZMsoBuyzEJxquxWSB8+r8cfZviVkoWPGMMiAfK8i5lhEcejOQ84fovb1jB8f1UOR48P+GYFGeRWPJyQ2G0xuYH7ZcGch7FPYrRYTH2iGI9h9I4gbTbzqeEuNXbg2CojVQvXopMlmhNezdFrXi0iKQ/MCNANTh1h1nDNlcjb67VYAB2nQj7kmc3LCDQKtZzWJyrEWzB6pswIUm78a+5s/FqWRhYrS/7FolbR8xr492uLQbrEJbhwU1zxjTYv4VR6JeWREm9A62vs/bHxZZAkSwBAfsMYhbUB1HSrG4kCjgNkWw==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: rm

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: proc
spec:
  encryptedData:
    root-password: AgABagbddKfvcd9wQXCcTQX4brTOfl6uExuKx45YSdttax0TBYAYLeCRvzB2HR29e64tWmZ0vCOp/mfSFEmAiwjkTpew5IMQU7N+VdCQAbdkcePo+OcmX4NhDxMnp+0PhuLKDvIr1FRLCeQ7tgdc/mMKPdkRm9h8j4fyQ5eAw4ACKht7Ol098paaVhEiQZhb+jDOQJITpdLlf5GDfVtuA/DFlyEXeQug1wa5gG6XlI5mx1z6SN4jH1osVuu5nffSx9YdHppRWXKH5yl+0E5MCEyY5D5tic5UtESdiNZOD9wR/CYhQb90utt1rYycLRYkqqr7EgihlRttufNFKrFZik53Rf5t/whS7OD1nc1316QhwL09fEQjhqRQ1lmk1oHGEoUKG/l0U5xkIyasIOB4KmDcwY5UAQCSMLsIAHt/8xkE2lbrqbLoPsRBjjN3CowT+PaCHN9EWfWeNxjP8gMZSI80yJ7hCG0ZEMC497EwyTR7pdCxeQyHPjzpX326zzNQlAJ5eP/IgKSLEErx+XTEmq8wnojIt8Qdi6vW9ffgWOAK0mAScipXr+WAJW+WHxRgB17Ip/D7FWaEsGftpf/KNjCdFp12U9seRrA0PsN4RFjDDRtxD+jd2I1e8d263HeqdE8Tjusv3bbh3G4sFoEj2SJA0mvg0Zzl+iYFswrX+dKOdSEU4a4NLbD3MS37FklCjoxeW4B7xV120sSSKyr0/L25toPd/ZQ1U3uI2GxAKNXhIPLWzC0bSI0M+1Czag/WiPpVWIOP7t4nNmKyICzr6CAk
    root-user: AgBP3h9UosJ9Qb0Oa3rhnqIGnJXD0dWaJMhUOCrZtN9/tS9wwMHXAigjGV/oVpb3bLEV68wJS4oFT3lFKxSbIFrqi8lvEgKvW40GgZCNojqjAktzEZzPUMmRVr10qWKQ3ubCfhso60SwLr+WuR8i8vRxd+Crv61BPcpH48D/OqB2r2Ex48bbgS0A8mOlygvWhPeUq/sTs6cnwGP/hyLfukkTLxcyRTyQRvnCaHYXmsbyXteLhSAi6mUMBEfkpbtqHYo1DxM52z3Q/uVuU457fmjdECnJRoixkKhPnN63qJLQfwguCOtjs6oq8dcqJ5YwdFzQM+mp7f5RJeqXK+wQLIJglbM5QuMynMSv4rT6KTH+X94nVF3jblKx/9QBKc2w1KQTgVdfQCNOEkkjIipD8buhT6E5zzGdXCGmd2hjsYM+CZlymapaL4+ohZpasHO/CsQ1vbkZtofrGw078gX9O7ctTMS0x70RFbpzSiLFI4+WlXCPS6/US2HSbPwAuCr0TKhdyJSIRWWzTwAvW9DigBLwEtfx7VE/Ep8DgbXxrehoOUj1WEVEyKxLIr2EQg1+YYGhTYroTk/wIUODDXq/VJd3rmfl5+b5qRyXxdAAFtT8VL01S5EPkbqW6mxzDns5pyyQ4Wqon+YU8G+/La+HpapjR14j1qtaOZhtLhjzVIq7oPM7rAJSPCQ+ykoHh5nm4lD1kLg8CQ==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: proc

