---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: eoepca-object-storage
spec:
  encryptedData:
    root-password: AgB4LnY6hSa6z6AtsH9F3r1UmCmlY1KODeROn3OTxExlnjRJaHAHVWqix1nbXddob+Yjif3eIcWuV5lKyzRhmutik8uPbjrn3w9nEjEvaZAsFx/5K91t7kgDi1jZDgYp2H9prlSjO6J7UWvri1jiexOg2aKtsyYkV7PEkOVrvkdTLYXgh3w3Y3c3/ltA8ZLLFXgwVEyTQiwX/zgZJVkPE5D4vQN1MK029aZaSXJ7NX2/0Cip/T7spI2djKF72RGW2TKB+iHt/RAQDHzgwcJE87GmWhfZeMmzzGfF3fq+qKNEGoh0pefBt/fW7iEMzvvM86iA71ebSXTk8UAdioLprf1eDU5LLyBV/U25+X1vms0eUFKcoz7fXokDVeBCPSWdah+tn1J9roL/hIR3+bHlSmLM0ino//3UdtczDFdba5ctwMhDI4wOq9S09DAl9Qbp7epO3pI4z0LOqDasrh7+aGt9LWDdb3r7pwcvGXxeyDQuM5oGrJnhfx8jSCygNYtYCpWH17Ova4tAemdvb8m0niQQlPzfceaaPna1QYqvQS3B+36AVz/L4I4zJuDx3dr7TZDOuQkhtrtjLLo/UTNv2g2T9Jk/SdvXJ4itx049v4nRIh7FW3yv2rHdMcqywrMC/HwrxGoil33qtDie+aLUOazmtX+9LZWVS64j/ZJfva/ENYCTuWH4LSRSTnaTYseX+ggv1Y0981nzuf23/94WX7qlGe6h7tug95d3+ULUOKdlBcR4d0CZ/fDQ6yrZ3+mp5ufQK5yCSBZvoKbiv72BK3PV
    root-user: AgAtMlmqvTt1gJFELtoTml0cNQ0PL3mT6T3HtUtEtTsVmm6P/qCIiLGW2jQKPSutWvriJSceIdaxOGnC4eKbQI739WtlDyl3+/2VXSedEq75MOtBD7BCt69EKsKsHCcGyCsoc8w3BAEUpIsTRB4N94vtM43BGINiTLCXJ14eYBOzPEG+lpiaWHo1fzGxxnoqCQ08Pq6XQyGBtuV83vJCd0bNia5Gq4v9FMjHuw4dFOXbEqBqn0gOSy2qAkDTkp/GTmAaMuokZFQfmS5gbRmPFN54ZSUP2kcvESj62JGvT3Ss+A0TgjG4cgxxBirQq/SJnNppJPrv80eMp5fyXOARfvTUNqNHwkuP4Xkl2kPAGfgXBd2iqibB0/eSQX6b+uFBH+/q1jFDaE3ArSN+n91Aev+nge0GNaNgGc4j5mQdXAgEVW0qrXMVhJt08crKE5oLbO5+zFH6fW18i3qlMm+TQ46qHm1Wo7PLOSkxdw7KwHLFsBoH5YaZwE5OvvbJp2nrnJ3A430Ue5Kx06B4VUlpf4XxYyUnZiS/UAdnJSLyowGcH9Hf98KT2DwA7kRDaQosXDwc608NV9UF8cnDEMDI+beu/iNE1GRMu2eSPnX/Sn4R55Zf65YrJJkbPZxyUaEibW/YDm0BbuEGgNUnfF+3Zxgt+RBgGe0ERNu08nqqoWMAEf6uDJR6bLiJIpJ0zr/SmUvbafTjwg==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: eoepca-object-storage

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: rm
spec:
  encryptedData:
    root-password: AgAlh4PyZfjThpXRhrGwYrCyRGLf6497PjjgPa0TcOUmAjiJ+V8B8HTLCPaOhpOROfDW7W+P0zeSZIc+zg/RF/bg9ZuKyNpAGXYJNTO8x/tqZr7LhPxs4NcEjB7yFqvEaK2XjtEBtop46ulg81t9rp3CP7Q3vcCUbYYZ5Kv77LTmiZDo7tgyCj26vpa/QuQH/w0nDgJM8PKg0yMSxrBpMqr+UY7nphCX7xZUEwkfOzFAxsvYkV9nfIvAdhvMAVD0h8E/FLVysVl0+/0+Lcp4V4Ly1ah1zKmvF+0T2ypxs8Y7XCeSKmphi2NCHhOZs/FF5bWvoFQUpfh92e0mlsFtzzD7GcPOdM6DETUXb2nEOsYtRaoq5Ui4MohvgQ8rrK79wikoGUukcgpGo6y0kSyjYHR0jS/uL2e/rypGNdw03nDIT5EPwj7Wnvda8B3fAi/xPAbCcgVycmyWzudrZXGwYUKj6y93e8QmFYxFCoUrDeGlS6YI7GV8OcMwtHsich4z5zajF3dJ4rNQsG1JzUBylpT3YCcFOwtdO1ApPU0c/TAazFSvN37vSi4eSaV4eflvg4zMUl/j+IfHK4C/8PNJ6sSetJEvLe9lqR7Ka83iio1ZCRVFpUNlZHuDHVVwPY3wHkC6Ol7CPJvyY6z2YO174E3Swa7O3ahLyNRkNcDWTKl68ODTgLoqnP+XIV+BUEba9hMnzmj+QmBuZe/C4pbT4TBcfUSWrWjiOzTz3JLH01Ut0y7RHOnydoaQijB7kv2296y6wVWYMayrZ8ExdcAWbZIh
    root-user: AgAv2p5YPt6/FY+HmhyK/JVR2BNCn+mICJ+J/3SbHPFd+CxQmV96PTh1qtfzTfX2f0zYgdl5Zp5KGCVA973KroiJnGBURuevOElqsGeEUp8nhj1jBxRxy0x2hzVKOTHd1+oltRWdvrDBWGVCJIi9AYRbLLpz1wtSBJRdGutev6PBPSkUM5sWqo6SzFrPmEpgphZMWfHy/siXuGiz4mfZAHhocODGhw9g+sIag4zKjaZmAkGds5J3NwFTM49Tl6YASnOl7UyxOi5nfP7ehsItcGVzyCAMIo/rncFOLTEgldfbswJ7cE6PsSc2p8wUM6rAYAAY+gkpVMwIEDWy5/DESWmczDbXSe1bYYDxftjLdE/zSFeSkL+qhV+ix5R5kanX/euVBpTqX+KUJmBkHdV6zRsFX6osKkqILnLtzLr+cHVG2bdblhw6Nb24BiTnE08+6ERGuFSCWEOlIULkTe9QB3a3U3UktnDLw3j5Q7V2BmgPUL7H+BJQLmjLtXMOVvfV7B2zr2vLqw8ptvN7+Inl3J/Jv9z78Fa3+qb4SJHe/wfD7xld6LvIM+e6msopjwG3V9X7g3sqBmwdC2ZKf13Fj0QLvF8Ozh+luNHw0+v0EAWD4XV/bHlx1e45S0McJ2bGnlWTUd/TByoA/JvMtRU3SqmMcD7KNru2kF2sUYRKVgJva0H7JxLZqtLgjIPLNIenJRJEZUmzng==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: rm

