---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: eoepca-object-storage
spec:
  encryptedData:
    root-password: AgAylSz3JmSX9tdHaAjQnHlzNh8bMh4pIa8eQY3H6DugdZDtEAgoMlAP2IfTSKhu5CbLG7+SGoJiDOigYVmUZ92ARrk1eoUiJKOD5Fzr9+ciEsh3iMUJwVNdojJw80ayBdfcNPz/F7f3ZOXUMxcqvuo7OW1HlbvTLZAmXXdhhqSdj3NCoJEVxv/foHs7IsIzehsJavoad3poqtHv91f/45BBosI/WMauza6fpRzJDqs8g1gsCzrSpyCOcE13l37BazBQEkCVnJxPUVzNhL8PX/CE6JTiBjWP7t7f7viHUSAGstoHoGHLpSfbh5JeENhRksc+1FIHJOV1ckOWwxWoI6m9oY91n6DKVsnJ1MLHa5Qau48W/6JuZ8TyT5I3H77tbN6BO2q2k3MFJ5SMlIzqqcC5fd6y977kZqQ6YTu8VH/nvUBZseWvTvOg4juMjF3hC6U+hvC9OSnJPZVxvHMpwHVZ6n8G/BLZpMxHb8qJeFm4okaZxOlfiO0HWxSu8DCg/kF3xvzRkMxzm/etrd5ARFgEgmVk9t6DsRxxYajZmEgr9GC54zOAJetAuODJjSQm26cwM2av6JneA1LaKj0u3yscg750OpQ5rn+K6bFcnuXQYL2opSQvnci9bGVJbldCFnM9iMAMvTarLZVgNz4diF9Ytzln7mCFz0YHBiLy+SUX75LD8HwFlcu8XKACuAz/aoWf0ngLtPEJuQB37Gg1vznhFb589bz1jtf9Ya667WBntDcnw6AKu5SiUI94yLURkElq5xHyW/sku7e7wkQpHCDO
    root-user: AgCGtcYX/kbo6Kn1f5IT0GxCrepZwVowsTiiNyrZmgEK5WAc1cZD968QGAh/7kY15A6DEq0sIexIkak61Unam/b7zOcmOYiW3JnV7qFVmTpwcL4WZbJBRdRuGmKkp3pgVndPsQuQISFpQUaQfucOjLnZeXvu9DQHJLn+ADkz8jUc1fh3xcC9ubqw33/ZOnfMXpm/EYOySxbrQ1KhT3ZvpbkVnoj2HgPfaTirHA3eCFEUCRCJMMvBonqDyhFnS8U5JqKbFSR1tz8jE9wfzkRVFFvb8fOWfdqq5g5UAJPWCT3zZpJZ14RnfGhGcrRryptdO6VNN6jMJrBhASkryt6vDku2L+KDSIoq7+u7FIlnrCNMh2J4lLWBQI1V7YcuCtLrIZSVBemPw/Ocy/4M2eReRhAtMqiu/It8PBo1jfQBtXKuznGTnDmUFsT3zvTjBgfScoe0+CQjSM0msvdUy/+L14tyuBhZAiCD1bx3n0IreS9Ban1uZyhciuQHHNXwu/IoWoQ+re/3VOw2v7d9IminEYu4lXoTqtqI2mI4Q5I+Z98wlgMIZkBt6Tn2GTsJFXG3T9v+DPiM9K3dKKvj3Vckiszq7jgMcNdBAp3tGr7mEBt+fUGke55azOwpoTgPEy6e9fzvgOyC+UE4/zV2w0LvoaC5CFZvyiFo/5xRtNov6hoxLoc0K6U3hEiJWRQftlKAk0hjLDVN/Q==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: eoepca-object-storage

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: rm
spec:
  encryptedData:
    root-password: AgBDiwySqPZeIy+mwrYej3f4O3nSCS4bbUsnop9rrVW28yKxzW6MlCYeno+RWvV5CZ9/JT/nBWyVCKxtvf+A+RHzxAM1/lzFaZlB3oNdLJ+XdfCwOYkJOVAPZ7J4dFOb6RG1Jtu+ltOjqOgRPl8GIGH/uadv7eYRYQjREwZu97ahAxmGuQTc+qTzfUKb0fqQuL8oeHy/W7E3XGyfGBcSYfc0qHcJSXDELK8eyONwyKMN8oVEzzCpckKcpjDzgnvTDgQ5KAIrkanoSSkNqbmHeIZlgP7neFzqOW6R9nKT8sYDHzjZuBqxTEC8UQVaR/q2K1pRTgehhiV5V0X5FF+e7YkmvFkqwZa8XGIUoXaIDQl9hOqJ+RPHp22WIeCtwWyX2rL7gTnfWqA/P5F7g5gVI31LTguZp0OKOnS1ZYUyonjXVFuB4JEXU7pi8QuUIkFZbQ/dwzIbIV9yfdhi+vz/70xbk89uhtKG+ogCuvnrUtx5GB3/z+hphiwgITH/tvbxwa8MaD81H0rh/LxR/77GP1wisNHaZUlMfl80OjUEcyDmnxHfuD1z3L+h/PzEndyU/O9xh5yZogY3GuLWETUkfWBqQo36MOOOfr3C28Df1In1p2paq2EXOjTQMrveDFWRzhVeFO4Y8gSbFRMTYy0g86QI3t9+Ia1pbb4T1eLegfbQe3zu4fkvudeS7r4h/iKf2JwbR5we6tJNNR+0lVy+TCWTm5ymbGHVgDPlgWyEgygoa5t1n9J2TpAzXPE/jGMO73qrgceKMe7xONk3crQZ68Ia
    root-user: AgAh0x7gyfxQl/j71bsgaEPxHN0QUAMHQ1AJcx4YE1qKsp0PGm6qSu6/eHPoU4KVuO8GU94mZQfJVzOMIAfoDevh31u4lbwg+fo/nGCSPzJClnH1Od6gsGgJUq1V6GQig8L4dV4vv9yX1p/BI5YbZSc5g3yCQtOzJ9P7B4zauwBnsceEJQkhvbZ0axM8C5Ax47oBy/plYMg3HxbKaSXgfUt2LEALGQ5mpzd2PeP5a0lLGlCJihf+SmAElU4931HlJ22d+KJySBfxjqjYxNRnh4YM4l5bN6/qbcSSlH5he0ux68hbMuSXN/PCKkKbnGxZqLXzY/UyPo4Ikn/f9heGXeEcPjEW4dkr8aDhCpPzsdRio8XLU4RJONCx8PXcP5m+jWv5AjtpyqH+NFMT2Mmi0NA1bQXrnn4YdoQ+SsmKEwBYEywP+N6RkbFGPkO+xDkW5xLleD4ZsPdQkGqk3q+2XJQ/DFTuky50qYL7YnhmriQahApmRpyqT23QAXp/CYaoAd3SDadCXNTECihxgU7SJSQsWdySJOE4dTB6zJtsCtysmZLlf9gOfqlb0gw0j+uygOGkZArfEop7Z3qXwtbBseOaGFxBiNX/xwY0OY6MJnGQsZpyeHsKAve217lnpAe2bJyxOlHa8NYWjiOMAL+MHLpho57aQ/GaolivwDNy3WO8ywIZxojignhLRZmPefJP5TCMN+r+Sg==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: rm

