apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: eoepca-object-storage
spec:
  encryptedData:
    root-psassword: AgBRdAm3t0uJPhKqqAtTz1ADTU/KdhJU45F78fQHqi2fUJ9D4f/pH5ufuhT2zzatVfuRkuCvZBV84+GD8V5GknESJ8srBDDyHl4GLwncQozZY3C5yGHoSqVX3sGAGV75jO7va9/IEbul1kl+FgmyJvaplRSubN1/PMXWHhcCdrzQqrbYHNXryc0uEameU7o/843i4DyQmCvF0iNGbxK3EAXWiWq+CnSyVy4jHxs3dWmSKaJokb5Nm7Cyj/3NAyXYU57nvYWHlK2pbCWNRLO4HRejcdl4W/vCGPN05cXkK5q8yyrZeIpcYk64MrzT7fr0MhEzxnADwUEQKMOSnMjOn6gpqo+Ib7wrpkvig6u1S9YOaILl7T+n+r8/RZk13H3CQwyvMk55PMyNk8HsIroP/9bVHtDReBKDEEslRPrceUBT5YsNwLwRswrw8LL7B7PqYqThD74sUbcDNnI/KXVMjL8RmpsJEqNa6aOmHb84n39MRD/6egrIo+E6uGc/pzu6T//5dMPWCxvNlMqsNGcpm+V00QnmhnLt/zra0O9glCcH5nPWP/1xcdbqYzzjE/47e9mAgsEvPr1UKZki17F3BTUXZBDLzQOa6hVqdeNJMZZLKbg96XzSElRXmndEKBA8TxMEZjRNWIkNKr+1BsbAOreIDTkZhju+edMlgGxQn0MlgMYCPK/9/bKTKxJBK/rn3OkpxZaTc438IcQQvNeHZmH47fiXdDg88CtnFWc55RfXzhU9nnLy7qjxF+nlbNYA31zLwUm9pQVyRpho8Ha3oPeH
    root-user: AgB/mncoBwSjCs0VDJJc8Xxr2jNwtj91v9qSrTo8QdK7+AnPM6DDcgWnu4No3mvR8FYZPOCKJpfJ/fLdKZAKwpNHleSLIbmxnfls3jcOnir4kOlG2b35e4uQKd7NMXpHAFjtgrkrfxsv5UQ1sAQw/QFquvTHgHR6AvyG3Je5k255Aj4Xi+RQLNaXdBkNh/X6LaWfDc3UgMd1sqbg/Og2Cb1XSkGijfnZNWCrikotvh9K15bs4nxO1r3UJmCdU1aSvNvPtcD98P27LnHXxQgKfLVBP6KFfGx3TI5ENT6MH+H1dlyijx840twqM1qmj4QBS4pROqUTS6lbAKN2ZWAumNuwzyO+XLS47OJpcW73CeYdQKmtxOJNDwbt+9h1De2dePXXhlvaPVxPWDp30mLkCYqosW28GvNUFyB3GhMzSYLf3BOhrMK5fUIhXrBgZlVI3MRGFmeebHWUETwzMzPRIhO4HYFkRpUyyBqAIgtofVl8WMzUwARguxljBjdxLjofN5V7ZTTZZ/lOo8efCJU03a2Vz+oktvLoNRlHEISJlAdBm9dF1rscq+QYTkCfbDvosPMGrEUffE99OpSXB2FWwX6l0t0N3mbrNG4xOfMw3RSOhE8B08WE+5vZ1WIMdTGdHv+3Nt2s5UZXIbFHrepM+cJ7SmUzjJOhZ+POPVU3qYDiolqV+k/mBq+X+ofqnYt/KCrCF8hz/A==
  template:
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: eoepca-object-storage

