apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: workspace-api
  namespace: rm
spec:
  interval: 5m
  chart:
    spec:
      chart: rm-workspace-api
      version: 1.3.3
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: eoepca-system
  values:
    fullnameOverride: workspace-api
    imagePullSecrets:
      - name: regcred
      
    ingress:
      hosts:
        - host: workspace-api.${domain}
          paths: ["/"]
      tls:
        - hosts:
            - workspace-api.${domain}
          secretName: workspace-api-tls

    prefixForName: "develop-user"
    workspaceSecretName: "bucket"
    namespaceForBucketResource: "rm"
    s3Endpoint: "https://minio.${domain}"
    s3Region: "us-east-1"
    harborUrl: "https://harbor.${domain}"
    harborUsername: "admin"
    harborPasswordSecretName: "harbor-credentials"
    umaClientSecretName: "rm-uma-user-agent"
    umaClientSecretNamespace: "rm"
    workspaceChartsConfigMap: "workspace-charts"
    bucketEndpointUrl: "http://minio-bucket-api:8080/bucket"
    pepBaseUrl: "http://workspace-api-pep:5576/resources"
