apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: workspace-api
  namespace: rm
spec:
  interval: 5m
  chart:
    spec:
      chart: rm-workspace-api
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: eoepca-system
  valuesFrom:
    - kind: Secret
      name: harbor-credentials
      valuesKey: password
      targetPath: harborPassword
  values:
    fullnameOverride: workspace-api

    ingress:
      hosts:
        - host: workspace-api.workspace.eoepca.org
          paths: ["/"]
      tls:
        - hosts:
            - workspace-api.workspace.eoepca.org
          secretName: workspace-api-tls

    prefixForName: "develop-user"
    workspaceSecretName: "bucket"
    namespaceForBucketResource: "rm"
    s3Endpoint: "https://minio.workspace.eoepca.org"
    s3Region: "us-east-1"
    harborUrl: "https://harbor.workspace.eoepca.org"
    harborUsername: "admin"
    umaClientSecretName: "rm-uma-user-agent"
    umaClientSecretNamespace: "rm"
    workspaceChartsConfigMap: "workspace-charts"
    bucketEndpointUrl: "http://minio-bucket-api:8080/bucket"
    pepBaseUrl: "http://workspace-api-pep:5576/resources"
