---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx
  namespace: eoepca-system
spec:
  interval: 2m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: eoepca-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: eoepca-system
  interval: 5m
  values:
    controller:
      ingressClassResource:
        default: true
      loadBalancerIP: 80.158.54.66
      service:
        type: NodePort
        nodePorts:
          http: 31080
          https: 31443
      publishService:
        enabled: false