apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rm-resource-catalogue
spec:
  interval: 5m
  chart:
    spec:
      chart: rm-resource-catalogue
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: common
  values:
    global:
      namespace: "{{ workspace_name }}"
    db:
      volume_storage_type: standard
    ingress:
      enabled: false
    pycsw:
      image:
        repository: geopython/pycsw
        pullPolicy: Always
        tag: "eoepca-staging"
      config:
        server:
          url: "https://resource-catalogue.{{ workspace_name }}.185-52-195-215.nip.io"
        metadata:
          identification_title: Resource Catalogue - {{ workspace_name }}
          provider_name: EOEPCA
          provider_url: https://eoepca.org/
