---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx
  namespace: ingress
spec:
  interval: 2m
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: ingress
spec:
  interval: 5m 
  chart:
    spec:
      chart: ingress-nginx
      # version: "<4"
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: ingress
  values:
    controller:
      config:
        ssl-redirect: false