---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: resource-catalogue
  namespace: rm
spec:
  interval: 5m 
  chart:
    spec:
      chart: rm-resource-catalogue
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: eoepca-system
  values:
    imagePullSecrets:
      - name: regcred
    global:
      namespace: rm
    db:
      volume_size: 5Gi
    ingress:
      enabled: ${enableResourceIngresses}
      name: resource-catalogue
      host: resource-catalogue.${domain}
      tls_host: resource-catalogue.${domain}
      tls_secret_name: resource-catalogue-tls
      annotations:
        cert-manager.io/cluster-issuer: ${certificateIssuer}
    pycsw:
      image:
        pullPolicy: Always
      config:
        server:
          url: https://resource-catalogue.${domain}/
          federatedcatalogues: https://sentinel2.browse.catalog.mundiwebservices.com/csw
