apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: workspace-api
  namespace: rm
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: rm-workspace-api
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: eoepca
        namespace: eoepca-system
  valuesFrom:
    - kind: Secret
      name: harbor-credentials
      valuesKey: password
      targetPath: harborPassword
  values:
    fullnameOverride: workspace-api
    imagePullSecrets:
      - name: regcred
    image:
      pullPolicy: Always
    ingress:
      enabled: ${enableResourceIngresses}
      hosts:
        - host: workspace-api.${domain}
          paths: ["/"]
      tls:
        - hosts:
            - workspace-api.${domain}
          secretName: workspace-api-tls

    prefixForName: ${workspaceUserPrefix}
    workspaceSecretName: "bucket"
    namespaceForBucketResource: "rm"
    s3Endpoint: "https://minio.${domain}"
    s3Region: "us-east-1"
    harborUrl: "https://harbor.${domain}"
    harborUsername: "admin"
    umaClientSecretName: "workspace-api-uma-user-agent"
    umaClientSecretNamespace: "rm"
    workspaceChartsConfigMap: "workspace-charts"
